config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :words do
    collection do
      get :matching
      get :renew_word
      get :view_error_log
    end
    member do
      post :check_up
    end
  end

  resources :units

  root 'words#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/change_sentence_to_be_text_in_word.rb
class ChangeSentenceToBeTextInWord < ApplicationRecord
end

app/models/mistake_record.rb
class MistakeRecord < ApplicationRecord
  belongs_to :user
  belongs_to :word
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :words
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :mistake_records
  has_many :words, through: :mistake_records
  
end

app/models/word.rb
class Word < ApplicationRecord

#mistake string 检查类型（正确错误，未检查）

  belongs_to :unit

  has_many :mistake_records
  has_many :users, through: :mistake_records

  def is_synonym?(synonym)
    self.synonym.split(',').include?(synonym)
  end

  def self.unit_or_search(button_attr, word)
    if button_attr == 'Search'
      where("spelling LIKE ?", "%#{word}%").includes(:unit, {:mistake_records => :user})
    elsif button_attr.present? && button_attr.include?('Unit')
      unit_num = button_attr.split(" ").last
      @unit = Unit.find_by_unit_number(unit_num)
      @words = @unit.words.includes(:unit, {:mistake_records => :user})
    else
      all.includes(:unit, {:mistake_records => :user})
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)
    @unit.save

    redirect_to '/'
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    @unit = Unit.find(params[:id])
    @unit.update!(unit_params)

    redirect_to '/'
  end

  private

  def unit_params
    params.require(:unit).permit(:unit_number, :input_status)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  before_action :find_word, only: [:edit, :update]
  before_action :authenticate_user!, :only => [:new, :match, :check_up]

  def index
    @units = Unit.all.order("unit_number ASC")
    @words = Word.unit_or_search(params[:commit], params[:word]).order('created_at DESC').page(params[:page]).per(5)
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    @unit = Unit.find(params[:word][:unit_id])
    @word.unit = @unit
    @word.save!
    redirect_to words_path
  end

  def edit
  end

  def update
    @unit = Unit.find(params[:word][:unit_id])
    @word.unit = @unit
    @word.update!(word_params)
    redirect_to words_path
  end

  def matching
    if params[:commit].present? && params[:commit] == 'View error log'
      @words = Word.where('mistake =?', 2)
      @word_synonym = []
    elsif Word.where(mistake: [0, nil]).where(exist_num: 1).present?
      @words = Word.where(mistake: [0, nil]).where(exist_num: 1).order("RAND()").page(params[:page]).per(6)
      @word_synonym = @words.sample(6).map{|w| w.synonym.split(',').sample}
    else
      @words = Word.where(mistake: [0, nil]).order("RAND()").page(params[:page]).per(6)
      @word_synonym = @words.sample(6).map{|w| w.synonym.split(',').sample}
    end

  end

  def renew_word
    Word.where("mistake !=?", 0).update_all(["mistake =?", 0])
    redirect_to matching_words_path
  end

  def check_up
    @word = Word.find(params[:id])
    @synonym = params[:word][:synonym]
    @user = current_user
    if @word.is_synonym?(@synonym)
      @word.mistake = 1
    else
      @word.mistake = 2
      @word.mistake_records.create!(word_id: @word.id, user_id: @user.id)
    end
    @word.save
  end

  private

  def find_word
    @word = Word.find(params[:id])
  end

  def word_params
    params.require(:word).permit(:spelling, :meaning, :word_type, :sentence, :synonym, :mistake, :exist_num)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/common/_footer.html.erb
<div class="col-md-12" style="height:30px">
<a href="#"></a>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header col-md-6">
      <a class="navbar-brand" href="/">TOEFLWord</a>
      <div class="container">
      	<div class="row">
          <div class="search-input col-md-6">
            <div id="custom-search-input">
              <%= form_tag(words_path, method: :get) do %>
                <div class="input-group col-md-12">
                  <%= text_field_tag :word, '', class: "form-control" %>
                  <span class="input-group-btn">
                    <button class="form_submit btn btn-info btn-lg" name="commit" type="submit" value="Search" >
                      <i class="glyphicon glyphicon-search"></i>
                    </button>
                  </span>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.present? %>
        <li style="float:left"><a href="#"><%= current_user.email %></a></li>
        <li class="pull-right">
          <%= link_to(destroy_user_session_path, method: :delete) do %>
          <span class="glyphicon glyphicon-log-out"> SignOut</span>
          <% end %>
        </li>
      <% else %>
        <li class="pull-right">
          <%= link_to(new_user_registration_path) do %>
          <span class="glyphicon glyphicon-user"> SignUp</span>
          <% end %>
        </li>
        <li style="float:right">
          <%= link_to(new_user_session_path) do %>
          <span class="glyphicon glyphicon-log-in"> LogIn</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TOEFLWord</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <%= render "common/navbar" %>
      </div>
      <%= yield %>
      <%= render "common/footer" %>
    </div>
  </body>
</html>

app/views/units/_form.html.erb
<%= simple_form_for @unit do |f|%>
<%= f.input :unit_number %>
<% input_status = t("unit.input_status") %>
<div class="btn-group" data-toggle="buttons">
  <% input_status.each do |status| %>
    <label class="btn btn-default">
      <%= f.radio_button :input_status, status %>
      <%= t(status) %>
    </label>
  <% end %>
</div>
<br><br>
<%= f.submit 'Sure', class: "btn btn-info" %>
<% end %>

<script>
  $("#unit_input_status").select2( { theme: "bootstrap"} );
</script>

app/views/units/edit.html.erb
<h3>Edit Unit</h3>
<br>
<%= render 'form' %>

app/views/units/new.html.erb
<h3>New Unit</h3>
<%= simple_form_for @unit do |f|%>
<%= f.input :unit_number %>
<%= f.submit 'Sure', class: "btn btn-info" %>
<% end %>

app/views/words/_form.html.erb
<%= simple_form_for @word do |f| %>
<%= f.input :spelling %>
<% min_num = Unit.where("input_status =?", "未完成").map(&:unit_number).min %>
<%= f.association :unit, collection: Unit.order(:unit_number).map{|u| [u.unit_number, u.id]}, selected: min_num %>
<%= f.input :meaning %>
<%= f.input :word_type %>
<%= f.input :sentence %>
<%= f.input :synonym %>
<%= f.input :exist_num %>
<%= f.submit "生成", class: "btn btn-info" %>
<% end %>
<script>
  $("#word_unit_id").select2( { theme: "bootstrap"} );
</script>

app/views/words/_match.html.erb
<div id="view_error_log">
  <table class="table table-hover">
  <tr>
    <th>number</th>
    <th>spelling</th>
    <th>meaning/type</th>
    <th>synonym</th>
    <th id="adjusting">Adjusting</th>
  </tr>
  <% @words.each_with_index do |word, i| %>
    <tr>
      <td><%= i + 1 %></td>
      <td><%= word.spelling %></td>
      <td><%= word.meaning %>/<%= word.word_type %></td>
      <td><%= word.synonym %></td>
      <td>X</td>
    </tr>
  <% end %>
  </table>
</div>

app/views/words/check_up.js.erb
<% if @word.mistake == 1 %>
$("#check_right-<%= @word.id %>").replaceWith("<td>√</td>");
<% else %>
$("#check_right-<%= @word.id %>").replaceWith("<td>X</td>");
<% end %>

app/views/words/edit.html.erb
<h4 align="center">修改词汇</h4>
<%= render 'form' %>

app/views/words/index.html.erb
<div class="allUnit">
  <% @units.each do |unit| %>
  <a class="btn">
    <%= form_tag words_path, :method => :get do %>
      <%= submit_tag "Unit #{unit.unit_number}", class: "btn btn-default" %>
    <% end %>
  </a>
  <% end %>
</div>
<div class="button">
  <button type="button" onclick="showToefl()" name="button" class="btn btn-sm btn-default" style="float:left">TOEFL Words</button>
  <a id="allHide" type="button" class="btn btn-sm btn-default" style="float:left">^收起</a>
</div>

<div class="pull-right" style="margin-bottom:10px">
  <%= link_to 'New Word', new_word_path, class:"btn btn-info" %>
</div>
<br><br>
<div class="row">
  <% @words.each do |word| %>
    <div class="panel panel-default">
      <div class="panel-heading text-left">
        <%= word.spelling %> : <%= word.meaning %>
        <% if current_user %>
          <% if word.mistake_records.where("user_id =?", current_user.id).count != 0 %>
            <span class="numbercircle notice notice-icon" ><%= word.mistake_records.where("user_id =?", current_user.id).count %></span>
          <% end %>
        <% end %>
        <p style="float:right">Unit <%= word.unit.unit_number %></p>
      </div>
      <div class="panel-body">
        <p>
          例句:
          <br><br>
          <%= word.sentence %>
          <br>
        </p>
        <hr>
        <p>
          近义词:
          <br><br>
          <%= word.synonym %>
        </p>
        <p style="float:right"><%= link_to 'edit', edit_word_path(word), class: "btn btn-primary" %></p>
      </div>
    </div>
  <% end %>
</div>
<div class="pull-right" style="margin-top:10px">
  <%= link_to 'Match Train', matching_words_path, class: "btn btn-warning"%>
</div>
<%= paginate @words, params: {commit: params[:commit]}  %>


<script>
$(document).ready(function(){
  $(".allUnit").hide();
  $("#allHide").hide()
  function showToefl(){
    $(".allUnit").show();
    $("#allHide").show()
    $("#allHide").parent().find('button').hide()
  }
  $("a").on("click", function(){
    $(".allUnit").hide();
    $("#allHide").hide()
    $("#allHide").parent().find('button').show()
  })
})

</script>

app/views/words/match.html.erb
<h1 align="center">matching</h1>
<div class="pull-right" style="margin-bottom:10px">
  <%= link_to 'View error log', match_words_path(commit: 'View error log'), :remote => true, class: "btn btn-success" %>
  <%= link_to 'renew', renew_word_words_path, class: "btn btn-warning" %>
</div>

<div id="view_error_log">
  <table class="table table-hover">
  <tr>
    <th>number</th>
    <th>spelling</th>
    <th>synonym</th>
    <th>option</th>
    <th id="adjusting">Adjusting</th>
  </tr>
  <% @words.each_with_index do |word, i| %>
    <tr>
      <td><%= i + 1 %></td>
      <td><%= word.spelling %></td>
      <%= simple_form_for :word, url: check_up_word_path(word), :remote => true,  html: {method: "post"} do |f| %>
      <td><%= f.select :synonym, options_for_select(@word_synonym)%></td>
      <td><%= f.submit 'Check Up', class: "btn btn-primary" %></td>
      <% end %>
      <% if word.mistake == 1 %>
      <td>√</td>
      <% elsif word.mistake == 2 %>
      <td>X</td>
      <% else %>
      <td id="check_right-<%= word.id %>"></td>
      <% end %>
    </tr>
  <% end %>
  </table>
</div>

<%= paginate @words %>

app/views/words/match.js.erb
$("#view_error_log").replaceWith("<%=j render 'match', :locals => {:words => @words} %>")

app/views/words/matching.html.erb
<h1 align="center">matching</h1>
<div class="pull-right" style="margin-bottom:10px">
  <%= link_to 'View error log', matching_words_path(commit: 'View error log'), :remote => true, class: "btn btn-success" %>
  <%= link_to 'renew', renew_word_words_path, class: "btn btn-warning" %>
</div>

<div id="view_error_log">
  <table class="table table-hover">
  <tr>
    <th>number</th>
    <th>spelling</th>
    <th>synonym</th>
    <th>option</th>
    <th id="adjusting">Adjusting</th>
  </tr>
  <% @words.each_with_index do |word, i| %>
    <tr>
      <td><%= i + 1 %></td>
      <td><%= word.spelling %></td>
      <%= simple_form_for :word, url: check_up_word_path(word), :remote => true,  html: {method: "post"} do |f| %>
      <td><%= f.select :synonym, options_for_select(@word_synonym)%></td>
      <td><%= f.submit 'Check Up', class: "btn btn-primary" %></td>
      <% end %>
      <% if word.mistake == 1 %>
      <td>√</td>
      <% elsif word.mistake == 2 %>
      <td>X</td>
      <% else %>
      <td id="check_right-<%= word.id %>"></td>
      <% end %>
    </tr>
  <% end %>
  </table>
</div>

<%= paginate @words %>

app/views/words/matching.js.erb
$("#view_error_log").replaceWith("<%=j render 'match', :locals => {:words => @words} %>")

app/views/words/new.html.erb
<h4 align="center">添加词汇</h4>

<%= render 'form' %>